In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Reading data

In [4]:
df = pd.read_csv('data/house-prices.csv')

X = df[['SqFt', 'Bedrooms', 'Bathrooms', 'Offers', 'Brick', 'Neighborhood']]
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

## Data preprocessing and cleaning

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Price         128 non-null    int64
 1   SqFt          126 non-null    float64
 2   Bedrooms      125 non-null    float64
 3   Bathrooms     127 non-null    float64
 4   Offers        126 non-null    float64
 5   Brick         128 non-null    object
 6   Neighborhood  128 non-null    object
dtypes: float64(4), int64(1), object(2)
memory usage: 7.1+ KB

In [6]:
#returns a new dataFrame that its cells is False if it wasnt NaN/None in the Original, and True if it was
df.isna()

     Price   SqFt  Bedrooms  Bathrooms  Offers  Brick  Neighborhood
0    False  False     False      False   False  False         False
1    False  False     False      False   False  False         False
2    False  False     False      False   False  False         False
3    False  False     False      False   False  False         False
4    False  False     False      False   False  False         False
..     ...    ...       ...        ...     ...    ...           ...
123  False  False     False      False   False  False         False
124  False  False     False      False   False  False         False
125  False  False     False      False   False  False         False
126  False  False     False      False   False  False         False
127  False  False      True      False   False  False         False

[128 rows x 7 columns]

In [7]:
#amount of NaN/None values in dataFrame
print(df.isna().sum())

Price           0
SqFt            2
Bedrooms        3
Bathrooms       1
Offers          2
Brick           0
Neighborhood    0
dtype: int64

In [8]:
#Statistical Description
df.describe()

               Price         SqFt    Bedrooms   Bathrooms      Offers
count     128.000000   126.000000  125.000000  127.000000  126.000000
mean   130427.343750  2001.666667    3.032000    2.448819    2.563492
std     26868.770371   212.387382    0.728852    0.514992    1.069550
min     69100.000000  1450.000000    2.000000    2.000000    1.000000
25%    111325.000000  1882.500000    3.000000    2.000000    2.000000
50%    125950.000000  2000.000000    3.000000    2.000000    3.000000
75%    148250.000000  2140.000000    3.000000    3.000000    3.000000
max    211200.000000  2590.000000    5.000000    4.000000    6.000000

In [9]:
#fill the null/NaN value with median in numeric columns
#cause midian is better than mean with outlier data

columns_with_nulls = ['SqFt', 'Bedrooms', 'Bathrooms', 'Offers']

for col in columns_with_nulls:
    X_train[col] = X_train[col].fillna(X_train[col].median())
    X_test[col] = X_test[col].fillna(X_train[col].median())
    df[col] = df[col].fillna(df[col].median())

In [10]:
#converting categorical columns to numeric format

df['Brick'] = df['Brick'].map({'No': 0, 'Yes': 1})

#One-Hot encoding
df = pd.get_dummies(df, columns=['Neighborhood'], drop_first=False)
#for converting bool to int
df *= 1
#One-Hot encoding
X_train['Brick'] = X_train['Brick'].map({'No': 0, 'Yes': 1})
X_test['Brick'] = X_test['Brick'].map({'No': 0, 'Yes': 1})

X_train = pd.get_dummies(X_train, columns=['Neighborhood'], drop_first=False)
X_test = pd.get_dummies(X_test, columns=['Neighborhood'], drop_first=False)

#Aligning Columns
#Handles missing categories in test data by initializing their columns with 0
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)
#for converting bool to int
X_train = X_train.astype(float)
X_test = X_test.astype(float)

X_test.info(), X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, 55 to 64
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SqFt                13 non-null     float64
 1   Bedrooms            13 non-null     float64
 2   Bathrooms           13 non-null     float64
 3   Offers              13 non-null     float64
 4   Brick               13 non-null     float64
 5   Neighborhood_East   13 non-null     float64
 6   Neighborhood_North  13 non-null     float64
 7   Neighborhood_West   13 non-null     float64
dtypes: float64(8)
memory usage: 936.0 bytes
<class 'pandas.core.frame.DataFrame'>
Index: 115 entries, 4 to 102
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SqFt                115 non-null    float64
 1   Bedrooms            115 non-null    float64
 2   Bathrooms           115 non-null    float64
 3   Offers              115 non-null    float64
 4   Brick               115 non-null    float64
 5   Neighborhood_East   115 non-null    float64
 6   Neighborhood_North  115 non-null    float64
 7   Neighborhood_West   115 non-null    float64
dtypes: float64(8)
memory usage: 8.1 KB

(None, None)